// Optional editor attribution: events captured by the VS Code extension
// (edit shape, never content), hash-chained for tamper evidence. Secondary to
// resolution history — PoryGen works without it.

import { useEffect, useMemo, useState } from "react";
import { verifyChain, type ProvenanceEvent } from "@porygen/provenance-core";
import { listProvenanceEvents } from "../../lib/api";
import type { ProvenanceEventRow, RepositoryRow } from "../../lib/dbTypes";
import { formatDateTime } from "../../lib/format";

function toChainEvent(row: ProvenanceEventRow): ProvenanceEvent {
  return {
    id: row.id,
    repositoryId: row.repository_id,
    ownerId: row.owner_id,
    filePath: row.file_path,
    sourceType: row.source_type,
    actorType: row.actor_type,
    provider: row.provider,
    tool: row.tool,
    commitSha: row.commit_sha,
    parentEventId: row.parent_event_id,
    contentHash: row.content_hash,
    diffHash: row.diff_hash,
    eventTimestamp: row.event_timestamp,
    metadata: row.metadata_json,
    previousEventHash: row.previous_event_hash,
    eventHash: row.event_hash,
    createdAt: row.created_at,
  };
}

const SOURCE_LABEL: Record<ProvenanceEventRow["source_type"], string> = {
  human: "Developer edit",
  ai: "Bulk insertion",
  imported: "Pasted or imported",
  generated: "Generated by tooling",
  unknown: "Unclassified",
};

export function AttributionLedger({ repositories, repositoryId, onRepositoryChange }: { repositories: RepositoryRow[]; repositoryId: string | null; onRepositoryChange: (id: string) => void }) {
  const [loaded, setLoaded] = useState<{ repositoryId: string; events: ProvenanceEventRow[]; chainIntact: boolean | null; error: string | null } | null>(null);
  const loading = repositoryId !== null && loaded?.repositoryId !== repositoryId;
  const events = loaded?.events ?? [];
  const chainIntact = loaded?.chainIntact ?? null;
  const error = loaded?.error ?? null;

  useEffect(() => {
    if (!repositoryId) return;
    let cancelled = false;
    listProvenanceEvents(repositoryId)
      .then(async (rows) => {
        const intact = rows.length > 0 ? (await verifyChain(rows.map(toChainEvent))).intact : null;
        if (!cancelled) setLoaded({ repositoryId, events: rows, chainIntact: intact, error: null });
      })
      .catch((err) => {
        if (!cancelled) {
          setLoaded({ repositoryId, events: [], chainIntact: null, error: err instanceof Error ? err.message : "Could not load editor attribution." });
        }
      });
    return () => {
      cancelled = true;
    };
  }, [repositoryId]);

  const composition = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const e of loaded?.events ?? []) counts[e.source_type] = (counts[e.source_type] ?? 0) + 1;
    return counts;
  }, [loaded]);

  return (
    <section aria-labelledby="attr-title">
      <div className="block-head">
        <h2 id="attr-title" className="block-title-lg">
          Editor attribution
        </h2>
        <select className="select" aria-label="Repository" value={repositoryId ?? ""} onChange={(e) => onRepositoryChange(e.target.value)}>
          {repositories.map((r) => (
            <option key={r.id} value={r.id}>
              {r.name}
            </option>
          ))}
        </select>
      </div>
      <p className="answer">
        Optional. The PoryGen VS Code extension records the shape of edits — size and timing, never content — and each event is
        hash-chained so later tampering is detectable. These are heuristics about how code arrived, not a determination of who
        or what wrote it.
      </p>

      {error && <p className="notice notice-error block-notice">{error}</p>}
      {loading ? (
        <div className="page-loading" role="status">
          Loading…
        </div>
      ) : events.length === 0 ? (
        <div className="empty block">
          <h3>No editor events for this repository.</h3>
          <p>Install the VS Code extension (packages/vscode-extension) to capture them. Scans and resolution history don't need it.</p>
        </div>
      ) : (
        <>
          <div className="kv block">
            <div className="kv-cell">
              <div className="kv-key">Events</div>
              <div className="kv-value">{events.length}</div>
            </div>
            <div className="kv-cell">
              <div className="kv-key">Hash chain</div>
              <div className="kv-value">{chainIntact ? "Intact — recomputes cleanly" : "Verification failed"}</div>
            </div>
            {Object.entries(composition).map(([source, count]) => (
              <div className="kv-cell" key={source}>
                <div className="kv-key">{SOURCE_LABEL[source as ProvenanceEventRow["source_type"]]}</div>
                <div className="kv-value">{count}</div>
              </div>
            ))}
          </div>
          <div className="table-wrap block">
            <table className="table">
              <thead>
                <tr>
                  <th scope="col">When</th>
                  <th scope="col">Signal</th>
                  <th scope="col">File</th>
                  <th scope="col">Tool</th>
                  <th scope="col">Event hash</th>
                </tr>
              </thead>
              <tbody>
                {events.map((e) => (
                  <tr key={e.id}>
                    <td>{formatDateTime(e.event_timestamp)}</td>
                    <td>{SOURCE_LABEL[e.source_type]}</td>
                    <td className="mono">{e.file_path}</td>
                    <td>{e.tool ?? "—"}</td>
                    <td className="mono">{e.event_hash.slice(0, 10)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="fine block">Local hash-chain attestation · unsigned in-toto statement. See docs/PROVENANCE.md.</p>
        </>
      )}
    </section>
  );
}
