-- Generated by scripts/seed-lattice.ts — do not hand-edit.

delete from public.provenance_events where repository_id = '00000000-0000-4000-8000-000000000001';

delete from public.scan_findings where scan_id = '00000000-0000-4000-8000-000000000002';

delete from public.scans where id = '00000000-0000-4000-8000-000000000002';

delete from public.repositories where id = '00000000-0000-4000-8000-000000000001';

insert into public.repositories
    (id, owner_id, name, provider, clone_url, default_branch, visibility, is_demo, last_scanned_at)
    values ('00000000-0000-4000-8000-000000000001', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', 'porygen/lattice', 'demo',
      'https://porygen.dev/demo/lattice', 'main', 'public', true, now());

insert into public.scans
    (id, repository_id, owner_id, status, policy_version, started_at, finished_at,
     files_scanned, dependencies_scanned, risk_level, summary_json)
    values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', 'complete', '2026.1',
      now() - interval '4 minutes', now() - interval '3 minutes', 62, 14, 'blocking', '{"languages":["python","typescript","javascript"],"referenceFingerprintsChecked":537,"clearFindings":1,"reviewFindings":2,"blockingFindings":1,"provenanceCoveragePercent":100,"terminalLog":["[ingest] repository manifest accepted (seeded fixture)","[index] 62 source files · 9,140 LOC","[ast] 6,318 syntax nodes normalized","[winnow] 537 fingerprints retained","[corpus] 62 files evaluated against 1 matching reference candidate","[license] AGPL-3.0 candidate found in dependency graph","[policy] blocking"],"provenanceComposition":{"human":61,"ai":27,"humanModifiedAi":8,"unknown":4},"repoContentHash":"b6e9883d1aa5ff7e"}'::jsonb);

insert into public.scan_findings
      (scan_id, type, severity, title, file_path, confidence, evidence_json, remediation)
      values ('00000000-0000-4000-8000-000000000002', 'license', 'blocking', 'AGPL-3.0 dependency "lattice-forms" detected', null,
        null, '{"name":"lattice-forms","version":"2.3.0","ecosystem":"npm","license":"AGPL-3.0","source":"manifest"}'::jsonb, 'AGPL-3.0 carries strong copyleft obligations under the default commercial policy — route to counsel review before distribution.');

insert into public.scan_findings
      (scan_id, type, severity, title, file_path, confidence, evidence_json, remediation)
      values ('00000000-0000-4000-8000-000000000002', 'structural_similarity', 'review', 'Structural fingerprint match: quicksort(items) reference implementation', 'src/sort/order.py',
        1, '{"corpusEntryId":"ref-quicksort-py","corpusEntryLicense":"AGPL-3.0","containment":1,"sharedFingerprints":20,"corpusFingerprints":20,"note":"Structural fingerprint match against configured reference corpus."}'::jsonb, 'Compare against the referenced corpus entry and confirm independent authorship or required attribution.');

insert into public.scan_findings
      (scan_id, type, severity, title, file_path, confidence, evidence_json, remediation)
      values ('00000000-0000-4000-8000-000000000002', 'provenance_mix', 'review', 'AI-assisted function insertion followed by substantial developer editing', 'src/api/rateLimiter.ts',
        null, '{"classification":"MIXED_PROVENANCE","aiInsertion":{"lines":126,"elapsedMs":184},"humanModification":{"edits":31,"elapsedMinutes":14}}'::jsonb, 'No policy action required — logged as mixed provenance for the audit trail.');

insert into public.scan_findings
      (scan_id, type, severity, title, file_path, confidence, evidence_json, remediation)
      values ('00000000-0000-4000-8000-000000000002', 'license', 'info', 'npm dependency "lattice-utils" — MIT', null,
        null, '{"name":"lattice-utils","version":"1.8.2","ecosystem":"npm","license":"MIT","source":"registry-lookup"}'::jsonb, null);

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000000', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/forms/validators.ts',
        'a1c9f02', 'de27e10358b827d83e4e274a2abc8d83f299296d04b3a95ca668ee6842b55b7e', '1bcad7723db9ac82',
        '2026-09-15T09:02:00.000Z', '{"classifierSignal":"human_signal","insertedChars":22}'::jsonb, null,
        '5c33ac0b450d9a5744a4a8bce9f780d1723b9c8c7da31c12c52063087b7c2c0b');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000001', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/forms/validators.ts',
        'a1c9f02', '4258321bdbcd402dbf55e8fc5579a593f1415311d1b455b53a66855584ed67df', 'b261095336aba10e',
        '2026-09-15T09:04:00.000Z', '{"classifierSignal":"human_signal","insertedChars":25}'::jsonb, '5c33ac0b450d9a5744a4a8bce9f780d1723b9c8c7da31c12c52063087b7c2c0b',
        '1b60767ecfe9b59110a637de260feafaed764165d93a67559927d6548cb856ce');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000002', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/forms/validators.ts',
        'a1c9f02', '9dd8cf01f3b89cfff36f835f5381bdc3272ec732efa068adcc3634edbe0448b7', '66cea4f7639ff87d',
        '2026-09-15T09:06:00.000Z', '{"classifierSignal":"human_signal","insertedChars":28}'::jsonb, '1b60767ecfe9b59110a637de260feafaed764165d93a67559927d6548cb856ce',
        '3a34ab3053ee3321cf7d507e7b477d08b4c02ba93e73ad8209332cc1d0979fbb');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000003', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/forms/validators.ts',
        'a1c9f02', 'f22830ba608869b378be6ef843b4d17c076f74750c2068b50b6136edca177739', '9ca7ea480ae94aba',
        '2026-09-15T09:08:00.000Z', '{"classifierSignal":"human_signal","insertedChars":31}'::jsonb, '3a34ab3053ee3321cf7d507e7b477d08b4c02ba93e73ad8209332cc1d0979fbb',
        'a87a66fdaddd84078dc04d0ba5abf207f35c40ccc4db679e16b51a55cead444a');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000004', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/forms/validators.ts',
        'a1c9f02', '971928af7222080d612a22431cecb8fdb9ea3f78171471f53f0c1ce54883ed12', '85a93da082ff2304',
        '2026-09-15T09:10:00.000Z', '{"classifierSignal":"human_signal","insertedChars":34}'::jsonb, 'a87a66fdaddd84078dc04d0ba5abf207f35c40ccc4db679e16b51a55cead444a',
        'cd68ff780110b52a9f94e8d0a3b843bfb8a26a6af417565f086f402385f657db');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000005', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/forms/validators.ts',
        'a1c9f02', 'e52e7ec3a397c44524cd2e00bb2d68c65b65353221ca39b0e4d58411454ddfe2', 'cd5f8dfa9f02e6c2',
        '2026-09-15T09:12:00.000Z', '{"classifierSignal":"human_signal","insertedChars":37}'::jsonb, 'cd68ff780110b52a9f94e8d0a3b843bfb8a26a6af417565f086f402385f657db',
        '8b1606423d00d095224561446ab5513b73b89c17134862110922df1e533d5057');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000006', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'imported', 'external',
        'manual-copy', null, 'vendor/leftpad.js',
        'a1c9f02', 'b86b2f23e3ac0dd1da4e1e40647d9963ed7d8876e56e2fbfa3499c3c7b952e49', '927b9be4e3861a95',
        '2026-09-15T09:17:00.000Z', '{"classifierSignal":"imported","insertedChars":812}'::jsonb, '8b1606423d00d095224561446ab5513b73b89c17134862110922df1e533d5057',
        '3152a4fea8a5b5302a1b265c6cb4a268795169727251049de71a950f35aefb29');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000007', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'ai', 'assistant',
        'github-copilot', 'GitHub Copilot', 'src/api/rateLimiter.ts',
        'b774de1', '6603fbb81477e6433e28c04200dcc07a4426802654e00530d86945d546d4c451', '817a8cf66b686184',
        '2026-09-15T09:25:00.000Z', '{"classifierSignal":"ai_assisted_signal","insertedLines":126,"elapsedMs":184}'::jsonb, '3152a4fea8a5b5302a1b265c6cb4a268795169727251049de71a950f35aefb29',
        '0e76c36da4ce09201b65b7d917c923653753c8a1c23aa43863531987149a07b5');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000008', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/api/rateLimiter.ts',
        'b774de1', '2067a0429f61d2076051102216c599937967f982e7c5e51df27c7840aa3e9e59', 'cbc4ce2dc9a1ff47',
        '2026-09-15T09:28:00.000Z', '{"classifierSignal":"human_modified_ai","editIndex":1}'::jsonb, '0e76c36da4ce09201b65b7d917c923653753c8a1c23aa43863531987149a07b5',
        '31bceb0058e1043b291b082932b12a7086d6e0ac65f4f4a62aee5584e368e17f');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000009', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/api/rateLimiter.ts',
        'b774de1', '13f9fefe7ee5098e830c97223f106ec7822256f79ec19e07ebe1419f13c1c8d2', 'df5e4d7c3b15331b',
        '2026-09-15T09:31:00.000Z', '{"classifierSignal":"human_modified_ai","editIndex":2}'::jsonb, '31bceb0058e1043b291b082932b12a7086d6e0ac65f4f4a62aee5584e368e17f',
        '4a0dc04217a40f7ca237053972f9173fd34f8d76ed2bc860147857bb2815820b');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000010', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/api/rateLimiter.ts',
        'b774de1', '8b5b6c0a94afd37098020cb55a6c8dfe98ba74f80d1d8486c64e1882f4b213a2', '06911e5158006348',
        '2026-09-15T09:34:00.000Z', '{"classifierSignal":"human_modified_ai","editIndex":3}'::jsonb, '4a0dc04217a40f7ca237053972f9173fd34f8d76ed2bc860147857bb2815820b',
        '5825513ec4e5cd5472147d411043b72549e7130b9ad5b07688f7cb3a7df6ed52');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000011', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/api/rateLimiter.ts',
        'b774de1', '3b83ae9b7eba3d0976e3a923162b4b2986aa0d4aeddf84c767827f05fa027ca8', '15e8790604fb2000',
        '2026-09-15T09:37:00.000Z', '{"classifierSignal":"human_modified_ai","editIndex":4}'::jsonb, '5825513ec4e5cd5472147d411043b72549e7130b9ad5b07688f7cb3a7df6ed52',
        'b41624583f106a6706bdd7c0d75b140d592e0d42762b0fed5febba1f377ecb24');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000012', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/api/rateLimiter.ts',
        'b774de1', '9b137f0fb024ae6a08efcba0d1d5a4dcbcc0550bf4ed5fe280aad7164d408e88', 'e7970329a149236d',
        '2026-09-15T09:40:00.000Z', '{"classifierSignal":"human_modified_ai","editIndex":5}'::jsonb, 'b41624583f106a6706bdd7c0d75b140d592e0d42762b0fed5febba1f377ecb24',
        '891c22d9de5c6b4b0de71e2f0d6bc3960c28b9aa02c26d32b3d7afe9de489351');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000013', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/utils/debounce.js',
        'c92a10f', '62c36245206c6ac8624d7a984d9ade13dc271960b2762d7946793417f3ba5432', '1b25e4df448215cf',
        '2026-09-15T09:42:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '891c22d9de5c6b4b0de71e2f0d6bc3960c28b9aa02c26d32b3d7afe9de489351',
        '75cfc7f9424d2eb8e320e17c78a026dc45644198049940d4c2829c31ec6110db');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000014', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/utils/debounce.js',
        'c92a10f', '96833a839cd2bbd4042f7195cb55e2f407a4a1e0c4b4498035cec6220b21b400', 'd610e74f9f7eb567',
        '2026-09-15T09:44:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '75cfc7f9424d2eb8e320e17c78a026dc45644198049940d4c2829c31ec6110db',
        '45b073a5f2278f14c503f2be7bc4dc7ed69efc5aa2ae7ad8d9bbf425a7283f88');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000015', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/utils/debounce.js',
        'c92a10f', 'ec8b095a8bf493a9ddc97fa73120c9f0906647fe04b240c4f49730ac6c674d3a', '9a88a53aced0722e',
        '2026-09-15T09:46:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '45b073a5f2278f14c503f2be7bc4dc7ed69efc5aa2ae7ad8d9bbf425a7283f88',
        '655770f0b550ec52734987888a1357c18a4c098103987b76cdd75398cab0d239');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000016', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/utils/debounce.js',
        'c92a10f', 'cd005212a8f624cbcf9300ecb4385faf908adfa50d46f40cb4a4fd98bcdcb31e', '00477da686d132bc',
        '2026-09-15T09:48:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '655770f0b550ec52734987888a1357c18a4c098103987b76cdd75398cab0d239',
        '1ef910221426554fe8b7faf2d341b11202e81d07f1b3586e32ad000a813015eb');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000017', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/utils/debounce.js',
        'c92a10f', '8b6d12c193ca50299552a73e1db63a3aee84459fdfe9ec59e2c3565378fa236b', '41b46a0a3fe8a803',
        '2026-09-15T09:50:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '1ef910221426554fe8b7faf2d341b11202e81d07f1b3586e32ad000a813015eb',
        'baf039a35f8986d0d913310ac6c43aca2f03a433e5e6163f120e9205f47a5a5e');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000018', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/utils/debounce.js',
        'c92a10f', '2dda0bb20b04a9751ab2c8a01f393ca932056d97befbae582d308b9912315e85', 'b05920a34fb910e8',
        '2026-09-15T09:52:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, 'baf039a35f8986d0d913310ac6c43aca2f03a433e5e6163f120e9205f47a5a5e',
        'e7758bd6b8aa5a2fcaa13baed028623fb3a497dc2fb65abf9668f249b6582bcf');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000019', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'generated', 'automation',
        'internal', 'docs-generator', 'README.md',
        'd05b7e2', '7c2395ffe3b24aca81423f589ad237cf399a57d6416ef98c778b9876399c10c5', '15ee53d784ef5daa',
        '2026-09-15T10:02:00.000Z', '{"classifierSignal":"unknown"}'::jsonb, 'e7758bd6b8aa5a2fcaa13baed028623fb3a497dc2fb65abf9668f249b6582bcf',
        '648ad2faf793f891a460979732f4c051f05a183e2b255d438854750f6f830f54');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000020', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/sort/order.py',
        'd05b7e2', '92738b8d9ea76a75c71219c9f73d0f41e42ac92c008ea9cfe03aca490846d796', '97e06c5296f399d1',
        '2026-09-15T10:06:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '648ad2faf793f891a460979732f4c051f05a183e2b255d438854750f6f830f54',
        'bb30fdbb94ce18616f7009a8080c257c7300b996d86d18da10b5e6004b0c36c4');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000021', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/sort/order.py',
        'd05b7e2', 'f9fb2b8c14b717ad3e7c6135ff153fc2c8b8d5b90ae12ad5aa37e8c242905849', 'e35f9b922d6c704f',
        '2026-09-15T10:10:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, 'bb30fdbb94ce18616f7009a8080c257c7300b996d86d18da10b5e6004b0c36c4',
        'e82ee3f6394bc38d58cbf41cfc66928b6b2d62f1814e68b012e6ca607cedc583');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000022', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/sort/order.py',
        'd05b7e2', '5ad4e826745a0cfbaf7f36cbc4cdd14aaccdec87ae6a8c939377555383d81325', 'fb1d8edce169d709',
        '2026-09-15T10:14:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, 'e82ee3f6394bc38d58cbf41cfc66928b6b2d62f1814e68b012e6ca607cedc583',
        '3c1819cec8c948f673f1be3dbdbea30f6591336397033d42723d5fe4ba2ff461');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000023', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'human', 'developer',
        null, null, 'src/sort/order.py',
        'd05b7e2', '3f813d06c6c1fe1859bcd13e18cb1fcbe6d3c0270b94160eb977f8a3e179f32c', '985a84111b242df9',
        '2026-09-15T10:18:00.000Z', '{"classifierSignal":"human_signal"}'::jsonb, '3c1819cec8c948f673f1be3dbdbea30f6591336397033d42723d5fe4ba2ff461',
        '089b3c20f8fef226a14933520ed582575f598b076e2809e9651d7ad9a7b7ed1a');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000024', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'unknown', 'external',
        null, null, 'src/utils/debounce.js',
        'e441fa9', '86d392cad97c8029e2ed019f792bd153ce8d4e49cc375f3a0b7f9da222a37b3a', '694b5cf9af6d53bf',
        '2026-09-15T10:24:00.000Z', '{"classifierSignal":"unknown"}'::jsonb, '089b3c20f8fef226a14933520ed582575f598b076e2809e9651d7ad9a7b7ed1a',
        'efd18889a5b247aab68997671e5ccd1eb9da6f0d8a1ec810006989f125556d78');

insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values ('00000000-0000-4000-9000-000000000025', 'aecb8db5-cd47-42f5-806f-c9d0a844a0ad', '00000000-0000-4000-8000-000000000001', 'unknown', 'external',
        null, null, 'README.md',
        'e441fa9', '959d41620b6c7dac5daef12cbc5d17100a4e9e6ffbf9b0e94b127b61c82e9473', 'efa3263bb28e8bff',
        '2026-09-15T10:27:00.000Z', '{"classifierSignal":"unknown"}'::jsonb, 'efd18889a5b247aab68997671e5ccd1eb9da6f0d8a1ec810006989f125556d78',
        '60c0161f194afc639a0527f0da7939f7561efd0aaec0f158e716a48194ebc5bc');
