#!/usr/bin/env tsx
// Generates deterministic SQL to seed the "Lattice" demo project: one
// repository, one completed scan, four representative findings (matching
// docs/DEMO_FLOW.md exactly), and a provenance ledger with genuinely
// computed hash-chain linkage and a genuinely computed structural-fingerprint
// match (Finding B is not hand-typed — it's the real winnowing output for an
// actual renamed/reformatted copy of the bundled quicksort corpus entry).
//
// Usage: npm run seed > scripts/lattice-seed.sql
// Then apply scripts/lattice-seed.sql via the Supabase SQL editor or MCP
// execute_sql/apply_migration (service-role / management access is required
// because these rows are owned by the fixed demo profile, not the caller).

import { buildChain, lexicalNormalize, fingerprintTokens, matchAgainstCorpus, sha256Hex } from "@porygen/provenance-core";
import type { ProvenanceEventInput } from "@porygen/provenance-core";

// Fixed so this script is idempotent and reviewable in a PR diff.
const DEMO_OWNER_ID = process.env.PORYGEN_DEMO_OWNER_ID ?? "aecb8db5-cd47-42f5-806f-c9d0a844a0ad";
const REPOSITORY_ID = "00000000-0000-4000-8000-000000000001";
const SCAN_ID = "00000000-0000-4000-8000-000000000002";

function sql(value: string | number | boolean | null): string {
  if (value === null) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${value.replace(/'/g, "''")}'`;
}

function jsonb(value: unknown): string {
  return `${sql(JSON.stringify(value))}::jsonb`;
}

async function main() {
  const statements: string[] = [];

  statements.push(`-- Generated by scripts/seed-lattice.ts — do not hand-edit.`);
  statements.push(`delete from public.provenance_events where repository_id = '${REPOSITORY_ID}';`);
  statements.push(`delete from public.scan_findings where scan_id = '${SCAN_ID}';`);
  statements.push(`delete from public.scans where id = '${SCAN_ID}';`);
  statements.push(`delete from public.repositories where id = '${REPOSITORY_ID}';`);

  // ---- Finding B: a REAL structural fingerprint match ----------------------
  // A renamed/reformatted copy of the bundled AGPL-3.0 quicksort corpus entry.
  const quicksortProbe = `def order(values):
    if len(values) <= 1:
        return values
    anchor = values[len(values) // 2]
    smaller = [v for v in values if v < anchor]
    equal = [v for v in values if v == anchor]
    larger = [v for v in values if v > anchor]
    return order(smaller) + equal + order(larger)`;
  const probeTokens = lexicalNormalize(quicksortProbe, "python");
  const probeFingerprints = fingerprintTokens(probeTokens);
  const matches = matchAgainstCorpus(probeFingerprints);
  const quicksortMatch = matches.find((m) => m.entryId === "ref-quicksort-py");
  if (!quicksortMatch) throw new Error("seed fixture regressed: quicksort probe no longer matches the reference corpus");

  // ---- Repository ------------------------------------------------------------
  statements.push(`insert into public.repositories
    (id, owner_id, name, provider, clone_url, default_branch, visibility, is_demo, last_scanned_at)
    values (${sql(REPOSITORY_ID)}, ${sql(DEMO_OWNER_ID)}, ${sql("porygen/lattice")}, ${sql("demo")},
      ${sql("https://porygen.dev/demo/lattice")}, ${sql("main")}, ${sql("public")}, true, now());`);

  // ---- Scan --------------------------------------------------------------------
  const summary = {
    languages: ["python", "typescript", "javascript"],
    referenceFingerprintsChecked: probeFingerprints.length + 512,
    clearFindings: 1,
    reviewFindings: 2,
    blockingFindings: 1,
    provenanceCoveragePercent: 100,
    terminalLog: [
      "[ingest] repository manifest accepted (seeded fixture)",
      "[index] 62 source files · 9,140 LOC",
      "[ast] 6,318 syntax nodes normalized",
      `[winnow] ${probeFingerprints.length + 512} fingerprints retained`,
      "[corpus] 62 files evaluated against 1 matching reference candidate",
      "[license] AGPL-3.0 candidate found in dependency graph",
      "[policy] blocking",
    ],
    provenanceComposition: { human: 61, ai: 27, humanModifiedAi: 8, unknown: 4 },
    repoContentHash: (await sha256Hex("porygen/lattice-fixture-v1")).slice(0, 16),
  };

  statements.push(`insert into public.scans
    (id, repository_id, owner_id, status, policy_version, started_at, finished_at,
     files_scanned, dependencies_scanned, risk_level, summary_json)
    values (${sql(SCAN_ID)}, ${sql(REPOSITORY_ID)}, ${sql(DEMO_OWNER_ID)}, ${sql("complete")}, ${sql("2026.1")},
      now() - interval '4 minutes', now() - interval '3 minutes', 62, 14, ${sql("blocking")}, ${jsonb(summary)});`);

  // ---- Findings A–D (exactly the four from docs/DEMO_FLOW.md) ------------------
  const findings = [
    {
      type: "license",
      severity: "blocking",
      title: `AGPL-3.0 dependency "lattice-forms" detected`,
      file_path: null,
      confidence: null,
      evidence: { name: "lattice-forms", version: "2.3.0", ecosystem: "npm", license: "AGPL-3.0", source: "manifest" },
      remediation: "AGPL-3.0 carries strong copyleft obligations under the default commercial policy — route to counsel review before distribution.",
    },
    {
      type: "structural_similarity",
      severity: "review",
      title: `Structural fingerprint match: ${quicksortMatch.entryTitle}`,
      file_path: "src/sort/order.py",
      confidence: Number(quicksortMatch.containment.toFixed(3)),
      evidence: {
        corpusEntryId: quicksortMatch.entryId,
        corpusEntryLicense: quicksortMatch.entryLicense,
        containment: quicksortMatch.containment,
        sharedFingerprints: quicksortMatch.sharedFingerprints,
        corpusFingerprints: quicksortMatch.corpusFingerprints,
        note: "Structural fingerprint match against configured reference corpus.",
      },
      remediation: "Compare against the referenced corpus entry and confirm independent authorship or required attribution.",
    },
    {
      type: "provenance_mix",
      severity: "review",
      title: "AI-assisted function insertion followed by substantial developer editing",
      file_path: "src/api/rateLimiter.ts",
      confidence: null,
      evidence: {
        classification: "MIXED_PROVENANCE",
        aiInsertion: { lines: 126, elapsedMs: 184 },
        humanModification: { edits: 31, elapsedMinutes: 14 },
      },
      remediation: "No policy action required — logged as mixed provenance for the audit trail.",
    },
    {
      type: "license",
      severity: "info",
      title: `npm dependency "lattice-utils" — MIT`,
      file_path: null,
      confidence: null,
      evidence: { name: "lattice-utils", version: "1.8.2", ecosystem: "npm", license: "MIT", source: "registry-lookup" },
      remediation: null,
    },
  ];

  for (const f of findings) {
    statements.push(`insert into public.scan_findings
      (scan_id, type, severity, title, file_path, confidence, evidence_json, remediation)
      values (${sql(SCAN_ID)}, ${sql(f.type)}, ${sql(f.severity)}, ${sql(f.title)}, ${f.file_path ? sql(f.file_path) : "null"},
        ${f.confidence !== null ? f.confidence : "null"}, ${jsonb(f.evidence)}, ${f.remediation ? sql(f.remediation) : "null"});`);
  }

  // ---- Provenance ledger: a real hash-chained event sequence --------------------
  const files = [
    "src/api/rateLimiter.ts",
    "src/sort/order.py",
    "src/forms/validators.ts",
    "src/utils/debounce.js",
    "vendor/leftpad.js",
    "README.md",
  ];
  const baseTime = new Date("2026-09-15T09:00:00.000Z").getTime();
  const inputs: ProvenanceEventInput[] = [];
  let cursor = baseTime;
  const commitShas = ["a1c9f02", "a1c9f02", "b774de1", "b774de1", "c92a10f", "d05b7e2", "d05b7e2", "e441fa9"];

  async function pushEvent(
    file: string,
    sourceType: ProvenanceEventInput["sourceType"],
    actorType: ProvenanceEventInput["actorType"],
    minutesLater: number,
    tool: string | null,
    provider: string | null,
    metadata: Record<string, unknown>,
    commitIndex: number,
  ) {
    cursor += minutesLater * 60_000;
    const contentHash = await sha256Hex(`${file}:${sourceType}:${cursor}`);
    inputs.push({
      ownerId: DEMO_OWNER_ID,
      repositoryId: REPOSITORY_ID,
      filePath: file,
      sourceType,
      actorType,
      provider,
      tool,
      commitSha: commitShas[commitIndex],
      contentHash,
      diffHash: (await sha256Hex(`${file}:${cursor}:diff`)).slice(0, 16),
      eventTimestamp: new Date(cursor).toISOString(),
      metadata,
    });
  }

  // Human-cadence edits on validators.ts
  for (let i = 0; i < 6; i++) {
    await pushEvent(files[2], "human", "developer", 2, null, null, { classifierSignal: "human_signal", insertedChars: 22 + i * 3 }, 0);
  }
  // Imported vendor file, single event
  await pushEvent(files[4], "imported", "external", 5, null, "manual-copy", { classifierSignal: "imported", insertedChars: 812 }, 1);
  // AI-assisted bulk insertion on rateLimiter.ts
  await pushEvent(files[0], "ai", "assistant", 8, "GitHub Copilot", "github-copilot", { classifierSignal: "ai_assisted_signal", insertedLines: 126, elapsedMs: 184 }, 2);
  // Human substantially reworks that AI insertion
  for (let i = 0; i < 5; i++) {
    await pushEvent(files[0], "human", "developer", 3, null, null, { classifierSignal: "human_modified_ai", editIndex: i + 1 }, 3);
  }
  // More human-cadence edits on debounce.js
  for (let i = 0; i < 6; i++) {
    await pushEvent(files[3], "human", "developer", 2, null, null, { classifierSignal: "human_signal" }, 4);
  }
  // Generated README update
  await pushEvent(files[5], "generated", "automation", 10, "docs-generator", "internal", { classifierSignal: "unknown" }, 5);
  // Structural-fingerprint-matched file, human-authored per repo history
  for (let i = 0; i < 4; i++) {
    await pushEvent(files[1], "human", "developer", 4, null, null, { classifierSignal: "human_signal" }, 6);
  }
  // A couple of genuinely unresolved events
  await pushEvent(files[3], "unknown", "external", 6, null, null, { classifierSignal: "unknown" }, 7);
  await pushEvent(files[5], "unknown", "external", 3, null, null, { classifierSignal: "unknown" }, 7);

  const chain = await buildChain(inputs, (i) => `00000000-0000-4000-9000-${String(i).padStart(12, "0")}`);

  for (const event of chain) {
    statements.push(`insert into public.provenance_events
      (id, owner_id, repository_id, source_type, actor_type, provider, tool, file_path, commit_sha,
       content_hash, diff_hash, event_timestamp, metadata_json, previous_event_hash, event_hash)
      values (${sql(event.id)}, ${sql(DEMO_OWNER_ID)}, ${sql(REPOSITORY_ID)}, ${sql(event.sourceType)}, ${sql(event.actorType)},
        ${event.provider ? sql(event.provider) : "null"}, ${event.tool ? sql(event.tool) : "null"}, ${sql(event.filePath)},
        ${event.commitSha ? sql(event.commitSha) : "null"}, ${sql(event.contentHash)}, ${event.diffHash ? sql(event.diffHash) : "null"},
        ${sql(event.eventTimestamp)}, ${jsonb(event.metadata ?? {})}, ${event.previousEventHash ? sql(event.previousEventHash) : "null"},
        ${sql(event.eventHash)});`);
  }

  console.log(statements.join("\n\n"));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
