import { useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { useDocumentTitle } from "../../components/useDocumentTitle";
import { acceptCurrentTerms, getTermsAcceptance, TERMS_VERSION } from "./termsAcceptance";
import "./terms.css";

const EFFECTIVE_DATE = "September 22, 2026";

function safeReturnPath(value: string | null) {
  if (!value || !value.startsWith("/") || value.startsWith("//")) return "/scan";
  return value;
}

export function TermsPage() {
  useDocumentTitle("Terms of Use");
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const existing = useMemo(() => getTermsAcceptance(), []);
  const [agreed, setAgreed] = useState(false);
  const [storageError, setStorageError] = useState("");
  const returnTo = safeReturnPath(params.get("return"));

  function accept() {
    if (!agreed) return;
    const acceptance = acceptCurrentTerms();
    if (!acceptance) {
      setStorageError("PoryGen could not record your acceptance in this browser. Enable local storage and try again.");
      return;
    }
    navigate(returnTo, { replace: true });
  }

  return (
    <main className="terms shell">
      <header className="terms-hero">
        <p className="label-caps">PoryGen Terms of Use</p>
        <h1 className="display terms-title">Read this before you scan.</h1>
        <p className="lede">
          PoryGen is an automated code-similarity research tool. Its findings can be useful, but they can also be incomplete,
          outdated, or wrong. These Terms define what the service does, what it does not do, and how responsibility is allocated.
        </p>
        <div className="notice notice-warn terms-warning">
          <strong>Important limitation.</strong> PoryGen can miss relevant source code and can flag unrelated code as similar.
          It does not determine copyright infringement, plagiarism, authorship, originality, license compliance, or whether code
          is legally safe to ship. Do not rely on a PoryGen result as your sole source of truth or as a substitute for legal,
          compliance, security, or other professional advice. Human review is required.
        </div>
        <p className="terms-meta">Effective {EFFECTIVE_DATE} · Version {TERMS_VERSION}</p>
      </header>

      <article className="terms-document">
        <section>
          <h2>1. Agreement to these Terms</h2>
          <p>
            These Terms of Use ("Terms") are a binding agreement between you and Gray Matter LLC, which operates PoryGen
            ("PoryGen," "we," "us," or "our"). By clicking "I agree and continue," accessing the scanning service after
            accepting these Terms, or using a PoryGen API or feature that expressly requires acceptance, you agree to these
            Terms. If you use PoryGen for an organization, you represent that you have authority to bind that organization.
          </p>
          <p>
            You must have legal capacity to enter into these Terms. If applicable law does not permit you to agree to a
            provision, that provision applies only to the maximum extent permitted by law.
          </p>
        </section>

        <section>
          <h2>2. What PoryGen provides</h2>
          <p>
            PoryGen compares supported source code against sources in its indexed corpus and returns automated similarity
            findings, source references, excerpts, metadata, license information, and related signals. Coverage is limited to
            the repositories, files, languages, versions, and source corpora actually checked during a scan.
          </p>
          <p>
            PoryGen is a research and review aid. It is not a law firm, legal service, certification authority, code-ownership
            registry, copyright adjudicator, malware scanner, security audit, or guarantee of provenance.
          </p>
        </section>

        <section>
          <h2>3. Automated analysis can be inaccurate</h2>
          <p>
            PoryGen uses automated and probabilistic techniques. Results may contain false positives, false negatives,
            incomplete matches, incorrect ranking, stale or incomplete license metadata, incorrect source attribution, broken
            third-party links, or other errors. A "no strong match" result means only that PoryGen did not find sufficiently
            strong evidence in the material it actually checked. It does not establish originality or legal clearance.
          </p>
          <p>
            A "strong match" or other similarity result is evidence for review, not proof that code was copied, generated by
            AI, unlawfully used, or subject to a particular legal obligation. You are responsible for evaluating findings,
            checking primary sources and applicable licenses, and obtaining qualified professional advice when appropriate
            before making legal, compliance, security, employment, commercial, takedown, shipping, or other material decisions.
          </p>
        </section>

        <section>
          <h2>4. Your responsibilities and representations</h2>
          <p>You agree that you will:</p>
          <ul>
            <li>use PoryGen only for lawful purposes and in compliance with applicable intellectual-property, privacy, computer-access, and data-protection laws;</li>
            <li>submit or direct PoryGen to content only when you are legally permitted to access and analyze that content;</li>
            <li>not use findings to knowingly make false accusations or misleading claims about a person, project, or organization;</li>
            <li>independently review material findings before acting on them;</li>
            <li>not attempt to bypass service limits, interfere with the service, scrape it abusively, probe it for vulnerabilities without authorization, or use it to distribute malicious code; and</li>
            <li>not reverse engineer or reproduce non-public PoryGen scoring, indexing, ranking, or source-intelligence technology except to the extent a restriction is prohibited by law.</li>
          </ul>
        </section>

        <section>
          <h2>5. Your code and scan data</h2>
          <p>
            As between you and PoryGen, you retain your rights in code and other content you submit or direct PoryGen to
            process. You grant PoryGen a limited, non-exclusive license to access, copy, transform, and analyze that content
            only as reasonably necessary to provide, secure, troubleshoot, and improve the service.
          </p>
          <p>
            For the current anonymous public-repository scanner, source code is fetched and analyzed transiently by PoryGen's
            servers and is not intentionally retained there after the request completes. Scan results, including matched code
            excerpts and your review or dismissal choices, may be stored in your browser's local storage. Browser storage is
            controlled by you and can generally be removed by clearing site data.
          </p>
        </section>

        <section>
          <h2>6. Third-party sources, links, packages, and licenses</h2>
          <p>
            PoryGen may display or link to material hosted by GitHub, npm, PyPI, package CDNs, open-source projects, or other
            third parties. Those materials remain subject to their owners' rights and applicable terms and licenses. A source
            reference does not mean that the source owner endorses PoryGen or agrees with a finding.
          </p>
          <p>
            License names, version information, repository identity, first-published dates, and similar metadata may be derived
            from third-party records and may be incomplete or inaccurate. You are responsible for reviewing the authoritative
            license text and source history before relying on that metadata.
          </p>
        </section>

        <section>
          <h2>7. PoryGen intellectual property</h2>
          <p>
            PoryGen and its non-public software, source-intelligence methods, indexes, ranking systems, interfaces, branding,
            documentation, and other service materials are owned by or licensed to Gray Matter LLC and are protected by
            applicable intellectual-property laws. These Terms give you a limited right to use the service; they do not transfer
            ownership of PoryGen technology to you.
          </p>
        </section>

        <section>
          <h2>8. Feedback</h2>
          <p>
            If you voluntarily provide ideas, suggestions, or feedback about PoryGen, you grant us a worldwide, perpetual,
            irrevocable, royalty-free right to use and incorporate that feedback without restriction or compensation, provided
            we do not identify you publicly as the source without permission.
          </p>
        </section>

        <section>
          <h2>9. Service changes and availability</h2>
          <p>
            PoryGen may add, remove, modify, suspend, rate-limit, or discontinue features, source coverage, supported languages,
            pricing, or availability. We do not promise uninterrupted operation, preservation of any particular corpus, or
            continued availability of third-party sources. Beta, experimental, free, and preview features may change or end
            without notice.
          </p>
        </section>

        <section>
          <h2>10. No warranties</h2>
          <p className="terms-caps">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, PORYGEN IS PROVIDED "AS IS" AND "AS AVAILABLE." GRAY MATTER LLC AND ITS
            MEMBERS, MANAGERS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS, LICENSORS, AND SUPPLIERS DISCLAIM ALL EXPRESS, IMPLIED,
            STATUTORY, AND OTHER WARRANTIES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
            NON-INFRINGEMENT, ACCURACY, COMPLETENESS, TITLE, QUIET ENJOYMENT, AND ANY WARRANTY ARISING FROM COURSE OF DEALING OR
            USAGE OF TRADE.
          </p>
          <p className="terms-caps">
            WE DO NOT WARRANT THAT PORYGEN WILL FIND ALL RELEVANT CODE, IDENTIFY THE TRUE OR ORIGINAL SOURCE, CLASSIFY A LICENSE
            CORRECTLY, DETECT INFRINGEMENT, DETERMINE AUTHORSHIP, PRODUCE ERROR-FREE RESULTS, OR OPERATE WITHOUT INTERRUPTION.
          </p>
        </section>

        <section>
          <h2>11. Limitation of liability</h2>
          <p className="terms-caps">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, GRAY MATTER LLC AND ITS MEMBERS, MANAGERS, OFFICERS, EMPLOYEES,
            CONTRACTORS, AGENTS, LICENSORS, AND SUPPLIERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
            EXEMPLARY, PUNITIVE, OR RELIANCE DAMAGES; LOST PROFITS, REVENUE, BUSINESS, GOODWILL, OR DATA; COSTS OF SUBSTITUTE
            SERVICES; OR LOSSES ARISING FROM YOUR RELIANCE ON A FINDING, FAILURE TO IDENTIFY A MATCH, LICENSE OR SOURCE
            INFORMATION, A THIRD-PARTY CLAIM, OR YOUR DECISION TO SHIP, MODIFY, REMOVE, ATTRIBUTE, LICENSE, DISCLOSE, OR STOP
            USING CODE.
          </p>
          <p>
            To the maximum extent permitted by law, the total aggregate liability of Gray Matter LLC and the persons and
            entities listed above for all claims arising out of or relating to PoryGen or these Terms will not exceed the
            greater of (a) the amount you paid PoryGen for the service during the 12 months before the event giving rise to the
            claim or (b) US $100.
          </p>
          <p>
            Nothing in these Terms excludes liability that cannot lawfully be excluded or limited, including liability to the
            extent caused by fraud, willful misconduct, or other conduct for which applicable law prohibits limitation.
          </p>
        </section>

        <section>
          <h2>12. Indemnification</h2>
          <p>
            To the extent permitted by law, you will defend, indemnify, and hold harmless Gray Matter LLC and its members,
            managers, officers, employees, contractors, and agents from third-party claims, damages, losses, liabilities, costs,
            and reasonable attorneys' fees arising from your unlawful use of PoryGen, your violation of these Terms, content you
            submit without sufficient rights, or your misuse or misrepresentation of PoryGen findings. This section does not
            require a consumer to indemnify PoryGen where such an obligation is prohibited by applicable law.
          </p>
        </section>

        <section>
          <h2>13. Third-party disputes</h2>
          <p>
            Disputes between you and a repository owner, package author, licensor, employer, customer, contractor, or other third
            party are between you and that third party. To the maximum extent permitted by law, PoryGen is not responsible for
            resolving those disputes or for losses arising from them.
          </p>
        </section>

        <section>
          <h2>14. Suspension and termination</h2>
          <p>
            You may stop using PoryGen at any time. We may suspend or terminate access if we reasonably believe your use violates
            these Terms, creates security or legal risk, abuses service resources, or must be restricted to comply with law.
            Sections that by their nature should survive termination, including intellectual-property, warranty, liability,
            indemnity, and dispute provisions, will survive.
          </p>
        </section>

        <section>
          <h2>15. Governing law and venue</h2>
          <p>
            Except where applicable law requires otherwise, these Terms are governed by the laws of the State of Alabama,
            without regard to conflict-of-law rules. Any dispute that is not required by law to be heard elsewhere will be
            brought in the state or federal courts located in or serving Montgomery County, Alabama, and you consent to their
            jurisdiction and venue.
          </p>
          <p>
            If you are a U.S. federal, state, or local government entity, provisions concerning governing law, venue,
            indemnification, or liability apply only to the extent permitted by the laws governing that entity.
          </p>
        </section>

        <section>
          <h2>16. Changes to these Terms</h2>
          <p>
            We may update these Terms as PoryGen changes. We will post the revised version and effective date. When a change is
            material, or when we otherwise determine renewed assent is appropriate, PoryGen may require you to accept the new
            version before another scan. Continued use after legally effective notice may constitute acceptance where permitted
            by law.
          </p>
        </section>

        <section>
          <h2>17. General terms</h2>
          <p>
            These Terms are the entire agreement between you and PoryGen concerning the service unless a separate written
            agreement applies. If a provision is unenforceable, it will be enforced to the maximum lawful extent and the
            remaining provisions will remain in effect. Failure to enforce a provision is not a waiver. You may not assign these
            Terms without our consent; we may assign them in connection with a merger, financing, reorganization, sale of assets,
            or transfer of the service.
          </p>
        </section>
      </article>

      <section className="terms-accept" aria-labelledby="terms-accept-title">
        <h2 id="terms-accept-title">Accept and continue</h2>
        {existing && (
          <p className="notice notice-ok">
            This browser previously accepted the current Terms on {new Date(existing.acceptedAt).toLocaleString()}.
          </p>
        )}
        <label className="terms-check">
          <input type="checkbox" checked={agreed} onChange={(event) => setAgreed(event.target.checked)} />
          <span>
            I have read and agree to the PoryGen Terms of Use, including the automated-analysis limitations, warranty
            disclaimers, and limitation of liability above.
          </span>
        </label>
        {storageError && <p className="notice notice-error">{storageError}</p>}
        <div className="terms-actions">
          <button type="button" className="btn btn-primary" disabled={!agreed} onClick={accept}>
            I agree and continue
          </button>
          <Link to="/" className="btn btn-ghost">Return home</Link>
        </div>
        <p className="hint">
          Your acceptance is recorded in this browser with the Terms version and acceptance time. Account-based acceptance
          records may be stored server-side when account scanning is enabled.
        </p>
      </section>
    </main>
  );
}
